<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.epam.automation</groupId>
    <artifactId>automation-advanced-course</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>21</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <selenium.version>4.41.0</selenium.version>
        <testng.version>7.12.0</testng.version>
        <juint-platform.version>1.12.1</juint-platform.version>
        <log4j.version>2.25.4</log4j.version>
        <reportportal.version>5.6.7</reportportal.version>
        <browserstack.sdk.version>1.57.0</browserstack.sdk.version>
        <surefire.version>3.2.2</surefire.version>
        <sonar.host.url>http://localhost:9000</sonar.host.url>
        <sonar.projectKey>automation-advanced-course</sonar.projectKey>
        <sonar.projectName>Automation Advanced Course</sonar.projectName>
        <sonar.coverage.jacoco.xmlReportPaths>
            ${project.reporting.outputDirectory}/jacoco/jacoco.xml
        </sonar.coverage.jacoco.xmlReportPaths>
        <sonar.coverage.exclusions>
            **/DriverFactory.java,
            **/driver/**,
            **/business/pages/**,
            **/business/models/**,
            **/business/components/**,
            **/business/service/**,
            **/api/business/controller/**,
            **/api/business/model/**,
            **/api/business/request/**,
            **/core/base/**,
            **/core/utils/WaitUtil.java,
            **/core/utils/ElementUtil.java,
            **/core/utils/ScreenshotUtil.java,
            **/core/logger/**,
            **/CucumberRunner.java,
            **/*Listener.java
        </sonar.coverage.exclusions>
    </properties>

    <dependencies>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>6.3.3</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.11.4</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>5.11.4</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>5.11.4</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <version>${juint-platform.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite-engine</artifactId>
            <version>${juint-platform.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <version>${juint-platform.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-commons</artifactId>
            <version>${juint-platform.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.27.7</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>client-java</artifactId>
            <version>5.4.11</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>agent-java-testng</artifactId>
            <version>${reportportal.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.epam.reportportal</groupId>
            <artifactId>logger-java-log4j</artifactId>
            <version>5.4.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.11.0</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>7.19.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>7.19.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>7.19.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>6.0.0</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.17.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.42</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>org.modelmapper</groupId>
            <artifactId>modelmapper</artifactId>
            <version>3.2.6</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.14.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <version>5.14.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
            <version>5.2.0</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>

        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>false</filtering>
            </testResource>
        </testResources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire.version}</version>
                <configuration>
                    <argLine>@{argLine}</argLine>
                    <includes>
                        <include>**/tests/unit/**/*Test.java</include>
                    </includes>
                    <excludes>
                        <exclude>**/launches_bdd/**</exclude>
                    </excludes>
                    <failIfNoTests>false</failIfNoTests>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version>
                <executions>
                    <execution>
                        <id>prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>21</release>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.42</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.sonarsource.scanner.maven</groupId>
                <artifactId>sonar-maven-plugin</artifactId>
                <version>5.0.0.4389</version>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>testng-class-parallel</id>
            <properties>
                <testng.config>testng.xml</testng.config>
            </properties>
        </profile>

        <profile>
            <id>junit-class-parallel</id>
            <build>
                <testResources>
                    <testResource>
                        <directory>src/test/resources</directory>
                        <includes>
                            <include>junit-platform.properties</include>
                        </includes>
                        <targetPath>.</targetPath>
                        <filtering>false</filtering>
                    </testResource>
                </testResources>
            </build>
        </profile>

        <profile>
            <id>cucumber</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${surefire.version}</version>
                        <configuration>
                            <includes>
                                <include>**/CucumberRunner.java</include>
                            </includes>
                            <excludes>
                                <exclude>**/launches_testng/**</exclude>
                                <exclude>**/launches_junit5/**</exclude>
                            </excludes>
                            <classpathDependencyExcludes>
                                <classpathDependencyExclude>org.testng:testng</classpathDependencyExclude>
                            </classpathDependencyExcludes>
                            <failIfNoTests>false</failIfNoTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>api</id>

            <activation>
                <property>
                    <name>tests</name>
                    <value>api</value>
                </property>
            </activation>

            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${surefire.version}</version>
                        <configuration>
                            <includes>
                                <include>**/tests/api/**/*Test.java</include>
                            </includes>
                            <excludes>
                                <exclude>**/launches_bdd/**</exclude>
                                <exclude>**/launches_testng/**</exclude>
                                <exclude>**/CucumberRunner.java</exclude>
                            </excludes>
                            <groups>api</groups>
                            <classpathDependencyExcludes>
                                <classpathDependencyExclude>org.testng:testng</classpathDependencyExclude>
                                <classpathDependencyExclude>com.epam.reportportal:agent-java-testng</classpathDependencyExclude>
                            </classpathDependencyExcludes>
                            <properties>
                                <configurationParameters>
                                    junit.jupiter.execution.parallel.enabled=false
                                </configurationParameters>
                            </properties>
                            <failIfNoTests>true</failIfNoTests>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>grid</id>
            <properties>
                <execution.mode>grid</execution.mode>
                <grid.url>http://localhost:4444/wd/hub</grid.url>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${surefire.version}</version>
                        <configuration>
                            <systemPropertyVariables>
                                <execution.mode>${execution.mode}</execution.mode>
                                <grid.url>${grid.url}</grid.url>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>selenoid</id>
            <properties>
                <execution.mode>selenoid</execution.mode>
                <selenoid.url>http://localhost:4444/wd/hub</selenoid.url>
            </properties>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${surefire.version}</version>
                        <configuration>
                            <argLine>@{argLine}</argLine>
                            <includes>
                                <include>**/tests/ui/launches_junit5/**/*Test.java</include>
                            </includes>
                            <excludes>
                                <exclude>**/launches_bdd/**</exclude>
                                <exclude>**/launches_testng/**</exclude>
                            </excludes>
                            <groups>ui_junit</groups>
                            <classpathDependencyExcludes>
                                <classpathDependencyExclude>org.testng:testng</classpathDependencyExclude>
                                <classpathDependencyExclude>com.epam.reportportal:agent-java-testng</classpathDependencyExclude>
                            </classpathDependencyExcludes>
                            <failIfNoTests>true</failIfNoTests>
                            <systemPropertyVariables>
                                <execution.mode>${execution.mode}</execution.mode>
                                <selenoid.url>${selenoid.url}</selenoid.url>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <profile>
            <id>browserstack</id>
            <dependencies>
                <dependency>
                    <groupId>com.browserstack</groupId>
                    <artifactId>browserstack-java-sdk</artifactId>
                    <version>${browserstack.sdk.version}</version>
                </dependency>
            </dependencies>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <version>${surefire.version}</version>
                        <configuration>
                            <argLine>
                                @{argLine} -javaagent:"${settings.localRepository}/com/browserstack/browserstack-java-sdk/${browserstack.sdk.version}/browserstack-java-sdk-${browserstack.sdk.version}.jar"
                            </argLine>
                            <systemPropertyVariables>
                                <execution.mode>browserstack</execution.mode>
                            </systemPropertyVariables>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>

    </profiles>

</project>
